## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: tests
  when:
    change: 'src/main.rs'
    run: cargo run watch -c 'echo $PATH'

- name: building
  when:
    change: 'src/**'
    run: cargo test
    ignore: '.event.yaml'

- name: tests
  when:
    change: 'tests/**'
    run: cargo test
    ignore: '.event.yaml'

- name: Starwars
  when:
    change: ".watch.yaml"
    run: telnet towel.blinkenlights.nl

