## Funzzy events file
# more details see: http://cristian.github.com/funzzy
#
# list here all the events and the commands that it should execute

- name: tests
  when:
    change: 'src/main.rs'
    run: cargo run watch -c 'echo $PATH'

- name: building
  when:
    change: 'src/**'
    run: cargo test

- name: tests
  when:
    change: 'tests/**'
    run: cargo test

- name: Starwars
  when:
    change: ".watch.yaml"
    run: telnet towel.blinkenlights.nl

