## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: building
  run: cargo test
  when:
    change: 'src/**'
    ignore: '.event.yaml'

- name: tests
  run: cargo test
  when:
    change: 'tests/**'
    ignore: '.event.yaml'

- name: Starwars
  run: telnet towel.blinkenlights.nl
  when:
    change: ".watch.yaml"

