[package]
name = "funzzy"
version = "0.3.3"
authors = ["Cristian Oliveira <contato@cristianoliveira.com.br>"]
description = "The fancy watcher inspired by entr."
license = "MIT"
repository = "https://github.com/cristianoliveira/funzzy"

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
notify = "^2.5.0"
yaml-rust = "0.3.2"
glob="0.2.11"
#clippy = "*"
